package view;

import java.rmi.Naming;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sd_aula09_arcondicionado.controller.ACInterface;
import sd_aula09_arcondicionado.controller.ACRMI;
import sd_aula09_light.controller.LightInterface;
import sd_aula09_light.controller.LightRMI;
import sd_aula09_smartdoor.controller.SmartDoorInterface;
import sd_aula09_smartdoor.controller.SmartDoorRMI;
import sd_aula09_smarttv.controller.SmartTvInterface;
import sd_aula09_smarttv.controller.SmartTvRMI;
import sd_aula09_waterheater.controller.AAInterface;
import sd_aula09_waterheater.controller.AARMI;

public class Smart_Home extends javax.swing.JFrame {

    private final AAInterface aaController;
    private final ACInterface acController;
    private final LightInterface liController;
    private final SmartDoorInterface sdController;
    private final SmartTvInterface stvController;

    public Smart_Home() throws Exception {
        initComponents();

        AARMI.main(null);
        ACRMI.main(null);
        LightRMI.main(null);
        SmartDoorRMI.main(null);
        SmartTvRMI.main(null);

        aaController = (AAInterface) Naming.lookup("rmi://LOCALHOST:10004/AquecedorAgua");
        acController = (ACInterface) Naming.lookup("rmi://LOCALHOST:10003/AC");
        liController = (LightInterface) Naming.lookup("rmi://LOCALHOST:10002/Light");
        sdController = (SmartDoorInterface) Naming.lookup("rmi://LOCALHOST:10001/SmartDoor");
        stvController = (SmartTvInterface) Naming.lookup("rmi://LOCALHOST:10000/SmartTV");

        visibilidadeComponentes();
    }

    private void visibilidadeComponentes() {
        //SmartTV
        CanaljLabel.setVisible(false);
        CanaljButton.setVisible(false);
        ValorCanaljLabel.setVisible(false);
        CanaljTextField1.setVisible(false);

        VolumejButton1.setVisible(false);
        VolumejLabel.setVisible(false);
        ValorVolumejLabel1.setVisible(false);
        VolumejTextField.setVisible(false);

        //Aquecedor
        TemAtualAAjLabel.setVisible(false);
        TempjButton.setVisible(false);
        ValorTempAtualjLabel1.setVisible(false);

        jTextField1.setVisible(false);

        //ArCondicionado
        TemperaturaAtualjLabel1.setVisible(false);
        ValorTempAtualjLabel2.setVisible(false);
        jTextField2.setVisible(false);

        TempjButton1.setVisible(false);
        WindjLabel.setVisible(false);
        ValorVentojLabel1.setVisible(false);
        WindjButton1.setVisible(false);

        //Luz
        IntensidadejLabel.setVisible(false);
        IntensidadejButton.setVisible(false);
        ValorIntensidadejLabel.setVisible(false);
        IntensidadejTextField1.setVisible(false);

        //Porta
        FecharPortajButton1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        abaHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        abaTV = new javax.swing.JPanel();
        PowerjButton = new javax.swing.JButton();
        CanaljLabel = new javax.swing.JLabel();
        ValorCanaljLabel = new javax.swing.JLabel();
        VolumejLabel = new javax.swing.JLabel();
        ValorVolumejLabel1 = new javax.swing.JLabel();
        LigaDesligajLabel = new javax.swing.JLabel();
        ValorLigaDesligajLabel1 = new javax.swing.JLabel();
        CanaljButton = new javax.swing.JButton();
        CanaljTextField1 = new javax.swing.JTextField();
        VolumejButton1 = new javax.swing.JButton();
        VolumejTextField = new javax.swing.JTextField();
        abaAquecedor = new javax.swing.JPanel();
        LigaDesligajLabel1 = new javax.swing.JLabel();
        ValorLigaDesligajLabel2 = new javax.swing.JLabel();
        PowerAAjButton1 = new javax.swing.JButton();
        TemAtualAAjLabel = new javax.swing.JLabel();
        ValorTempAtualjLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        TempjButton = new javax.swing.JButton();
        abaAr = new javax.swing.JPanel();
        LigaDesligajLabel2 = new javax.swing.JLabel();
        ValorLigaDesligajLabel3 = new javax.swing.JLabel();
        PowerACjButton2 = new javax.swing.JButton();
        TemperaturaAtualjLabel1 = new javax.swing.JLabel();
        ValorTempAtualjLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        TempjButton1 = new javax.swing.JButton();
        WindjLabel = new javax.swing.JLabel();
        ValorVentojLabel1 = new javax.swing.JLabel();
        WindjButton1 = new javax.swing.JButton();
        abaLuz = new javax.swing.JPanel();
        PowerjButton3 = new javax.swing.JButton();
        IntensidadejLabel = new javax.swing.JLabel();
        ValorIntensidadejLabel = new javax.swing.JLabel();
        LigaDesligajLabel3 = new javax.swing.JLabel();
        ValorLigaDesligajLabel4 = new javax.swing.JLabel();
        IntensidadejButton = new javax.swing.JButton();
        IntensidadejTextField1 = new javax.swing.JTextField();
        abaPorta = new javax.swing.JPanel();
        SenhajLabel = new javax.swing.JLabel();
        AppjLabel = new javax.swing.JLabel();
        ValorPortajLabel1 = new javax.swing.JLabel();
        SenhajButton = new javax.swing.JButton();
        SenhajTextField = new javax.swing.JTextField();
        FecharPortajButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Seja bem vindo(a)!");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Escolha um dos componentes da sua casa para controlar atraves das abas.");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casa-inteligente.png"))); // NOI18N

        javax.swing.GroupLayout abaHomeLayout = new javax.swing.GroupLayout(abaHome);
        abaHome.setLayout(abaHomeLayout);
        abaHomeLayout.setHorizontalGroup(
            abaHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaHomeLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaHomeLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(abaHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaHomeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaHomeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(263, 263, 263))))
        );
        abaHomeLayout.setVerticalGroup(
            abaHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaHomeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(54, 54, 54))
        );

        jTabbedPane1.addTab("Home", abaHome);

        PowerjButton.setBackground(java.awt.Color.white);
        PowerjButton.setText("Liga");
        PowerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerjButtonActionPerformed(evt);
            }
        });

        CanaljLabel.setText("Canal");

        ValorCanaljLabel.setText("12");

        VolumejLabel.setText("Volume");

        ValorVolumejLabel1.setText("12");

        LigaDesligajLabel.setBackground(java.awt.Color.red);
        LigaDesligajLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        LigaDesligajLabel.setText("Smart TV");

        ValorLigaDesligajLabel1.setText("Desligado");

        CanaljButton.setBackground(java.awt.Color.white);
        CanaljButton.setText("Alterar Canal");
        CanaljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanaljButtonActionPerformed(evt);
            }
        });

        VolumejButton1.setBackground(java.awt.Color.white);
        VolumejButton1.setText("Alterar Volume");
        VolumejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumejButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaTVLayout = new javax.swing.GroupLayout(abaTV);
        abaTV.setLayout(abaTVLayout);
        abaTVLayout.setHorizontalGroup(
            abaTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaTVLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(abaTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaTVLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(ValorLigaDesligajLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PowerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(abaTVLayout.createSequentialGroup()
                        .addGroup(abaTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaTVLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(ValorVolumejLabel1))
                            .addGroup(abaTVLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(ValorCanaljLabel)))
                        .addGap(87, 87, 87)
                        .addGroup(abaTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaTVLayout.createSequentialGroup()
                                .addComponent(VolumejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(VolumejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaTVLayout.createSequentialGroup()
                                .addComponent(CanaljTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(CanaljButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(abaTVLayout.createSequentialGroup()
                        .addGroup(abaTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CanaljLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VolumejLabel)
                            .addComponent(LigaDesligajLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        abaTVLayout.setVerticalGroup(
            abaTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaTVLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LigaDesligajLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorLigaDesligajLabel1)
                    .addComponent(PowerjButton))
                .addGap(24, 24, 24)
                .addGroup(abaTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(abaTVLayout.createSequentialGroup()
                        .addComponent(CanaljLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValorCanaljLabel))
                    .addGroup(abaTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CanaljTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CanaljButton)))
                .addGap(18, 18, 18)
                .addComponent(VolumejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorVolumejLabel1)
                    .addComponent(VolumejButton1)
                    .addComponent(VolumejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TV", abaTV);

        LigaDesligajLabel1.setBackground(java.awt.Color.red);
        LigaDesligajLabel1.setText("Aquecedor Água");

        ValorLigaDesligajLabel2.setText("Desligado");

        PowerAAjButton1.setBackground(java.awt.Color.white);
        PowerAAjButton1.setText("Liga");
        PowerAAjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerAAjButton1ActionPerformed(evt);
            }
        });

        TemAtualAAjLabel.setText("Temperatura Atual");

        ValorTempAtualjLabel1.setText("23");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        TempjButton.setBackground(java.awt.Color.white);
        TempjButton.setText("Alterar");
        TempjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaAquecedorLayout = new javax.swing.GroupLayout(abaAquecedor);
        abaAquecedor.setLayout(abaAquecedorLayout);
        abaAquecedorLayout.setHorizontalGroup(
            abaAquecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaAquecedorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(abaAquecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaAquecedorLayout.createSequentialGroup()
                        .addGroup(abaAquecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TemAtualAAjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LigaDesligajLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(abaAquecedorLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(abaAquecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaAquecedorLayout.createSequentialGroup()
                                .addComponent(ValorLigaDesligajLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PowerAAjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaAquecedorLayout.createSequentialGroup()
                                .addComponent(ValorTempAtualjLabel1)
                                .addGap(141, 141, 141)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(TempjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        abaAquecedorLayout.setVerticalGroup(
            abaAquecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaAquecedorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LigaDesligajLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaAquecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorLigaDesligajLabel2)
                    .addComponent(PowerAAjButton1))
                .addGap(24, 24, 24)
                .addGroup(abaAquecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(abaAquecedorLayout.createSequentialGroup()
                        .addComponent(TemAtualAAjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValorTempAtualjLabel1))
                    .addGroup(abaAquecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TempjButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Aquecedor", abaAquecedor);

        LigaDesligajLabel2.setBackground(java.awt.Color.red);
        LigaDesligajLabel2.setText("Ar Condicionado");

        ValorLigaDesligajLabel3.setText("Desligado");

        PowerACjButton2.setBackground(java.awt.Color.white);
        PowerACjButton2.setText("Liga");
        PowerACjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerACjButton2ActionPerformed(evt);
            }
        });

        TemperaturaAtualjLabel1.setText("Temperatura Atual");

        ValorTempAtualjLabel2.setText("23");

        TempjButton1.setBackground(java.awt.Color.white);
        TempjButton1.setText("Alterar");
        TempjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempjButton1ActionPerformed(evt);
            }
        });

        WindjLabel.setText("Vento");

        ValorVentojLabel1.setText("Desligado");

        WindjButton1.setBackground(java.awt.Color.white);
        WindjButton1.setText("Liga");
        WindjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WindjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaArLayout = new javax.swing.GroupLayout(abaAr);
        abaAr.setLayout(abaArLayout);
        abaArLayout.setHorizontalGroup(
            abaArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaArLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(abaArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaArLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(ValorLigaDesligajLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PowerACjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(abaArLayout.createSequentialGroup()
                        .addGroup(abaArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaArLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(ValorVentojLabel1))
                            .addGroup(abaArLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(ValorTempAtualjLabel2)))
                        .addGap(87, 87, 87)
                        .addGroup(abaArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WindjButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaArLayout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(TempjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(abaArLayout.createSequentialGroup()
                        .addGroup(abaArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TemperaturaAtualjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WindjLabel)
                            .addComponent(LigaDesligajLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        abaArLayout.setVerticalGroup(
            abaArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaArLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LigaDesligajLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorLigaDesligajLabel3)
                    .addComponent(PowerACjButton2))
                .addGap(24, 24, 24)
                .addGroup(abaArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(abaArLayout.createSequentialGroup()
                        .addComponent(TemperaturaAtualjLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValorTempAtualjLabel2))
                    .addGroup(abaArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TempjButton1)))
                .addGap(18, 18, 18)
                .addComponent(WindjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorVentojLabel1)
                    .addComponent(WindjButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ar", abaAr);

        PowerjButton3.setBackground(java.awt.Color.white);
        PowerjButton3.setText("Liga");
        PowerjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerjButton3ActionPerformed(evt);
            }
        });

        IntensidadejLabel.setText("Intensidade");

        ValorIntensidadejLabel.setText("23");

        LigaDesligajLabel3.setBackground(java.awt.Color.red);
        LigaDesligajLabel3.setText("Luz");

        ValorLigaDesligajLabel4.setText("Desligado");

        IntensidadejButton.setBackground(java.awt.Color.white);
        IntensidadejButton.setText("Alterar Intensidade");
        IntensidadejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntensidadejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaLuzLayout = new javax.swing.GroupLayout(abaLuz);
        abaLuz.setLayout(abaLuzLayout);
        abaLuzLayout.setHorizontalGroup(
            abaLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaLuzLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(abaLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaLuzLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(abaLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaLuzLayout.createSequentialGroup()
                                .addComponent(ValorLigaDesligajLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PowerjButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaLuzLayout.createSequentialGroup()
                                .addComponent(ValorIntensidadejLabel)
                                .addGap(56, 56, 56)
                                .addComponent(IntensidadejTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(IntensidadejButton))))
                    .addGroup(abaLuzLayout.createSequentialGroup()
                        .addGroup(abaLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LigaDesligajLabel3)
                            .addComponent(IntensidadejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        abaLuzLayout.setVerticalGroup(
            abaLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaLuzLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LigaDesligajLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorLigaDesligajLabel4)
                    .addComponent(PowerjButton3))
                .addGap(24, 24, 24)
                .addGroup(abaLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(abaLuzLayout.createSequentialGroup()
                        .addComponent(IntensidadejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValorIntensidadejLabel))
                    .addGroup(abaLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IntensidadejButton)
                        .addComponent(IntensidadejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Luz", abaLuz);

        SenhajLabel.setText("Senha:");

        AppjLabel.setBackground(java.awt.Color.red);
        AppjLabel.setText("Smart Door");

        ValorPortajLabel1.setText("Fechada");

        SenhajButton.setBackground(java.awt.Color.white);
        SenhajButton.setText("Verificar Senha");
        SenhajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhajButtonActionPerformed(evt);
            }
        });

        FecharPortajButton1.setBackground(java.awt.Color.white);
        FecharPortajButton1.setText("Fechar a Porta");
        FecharPortajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharPortajButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaPortaLayout = new javax.swing.GroupLayout(abaPorta);
        abaPorta.setLayout(abaPortaLayout);
        abaPortaLayout.setHorizontalGroup(
            abaPortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPortaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(abaPortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaPortaLayout.createSequentialGroup()
                        .addComponent(AppjLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(abaPortaLayout.createSequentialGroup()
                        .addComponent(SenhajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(abaPortaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(abaPortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaPortaLayout.createSequentialGroup()
                                .addComponent(SenhajTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                .addGap(62, 62, 62))
                            .addGroup(abaPortaLayout.createSequentialGroup()
                                .addComponent(ValorPortajLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(abaPortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SenhajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FecharPortajButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );
        abaPortaLayout.setVerticalGroup(
            abaPortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPortaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(abaPortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaPortaLayout.createSequentialGroup()
                        .addComponent(AppjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValorPortajLabel1))
                    .addComponent(FecharPortajButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SenhajLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaPortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SenhajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SenhajButton))
                .addGap(71, 71, 71))
        );

        jTabbedPane1.addTab("Porta", abaPorta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="SmartTV">
    private void VolumejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumejButton1ActionPerformed
        try {
            this.stvController.changeVolume(Integer.parseInt(this.VolumejTextField.getText()));
            ValorVolumejLabel1.setText(String.valueOf(stvController.getSmartTV().getVolume()));
        } catch (RemoteException ex) {
            Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VolumejButton1ActionPerformed

    private void CanaljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanaljButtonActionPerformed
        int channel = Integer.parseInt(this.CanaljTextField1.getText());
        try {
            this.stvController.changeChannel(channel);
            ValorCanaljLabel.setText(String.valueOf(stvController.getSmartTV().getChannel()));
        } catch (RemoteException ex) {
            Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_CanaljButtonActionPerformed

    private void PowerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerjButtonActionPerformed
        try {
            stvController.turnOffOn();
        } catch (RemoteException ex) {
            Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            if (!stvController.getSmartTV().isPowerButton()) {
                ValorLigaDesligajLabel1.setText("Desligado");
                PowerjButton.setText("Liga");

                visibilidadeComponentes();

            } else {
                ValorLigaDesligajLabel1.setText("Ligado");
                PowerjButton.setText("Desliga");

                CanaljLabel.setVisible(true);
                CanaljButton.setVisible(true);
                ValorCanaljLabel.setVisible(true);
                CanaljTextField1.setVisible(true);

                VolumejButton1.setVisible(true);
                VolumejLabel.setVisible(true);
                ValorVolumejLabel1.setVisible(true);
                VolumejTextField.setVisible(true);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PowerjButtonActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="AquecedorAgua">
    private void PowerAAjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerAAjButton1ActionPerformed
        try {
            aaController.turnOffOn();

            if (!aaController.getAquecedor().isPowerButton()) {
                ValorLigaDesligajLabel2.setText("Desligado");
                PowerAAjButton1.setText("Liga");

                TemAtualAAjLabel.setVisible(false);
                TempjButton.setVisible(false);
                ValorTempAtualjLabel1.setVisible(false);
                jTextField1.setVisible(false);

            } else {
                ValorLigaDesligajLabel2.setText("Ligado");
                PowerAAjButton1.setText("Desliga");

                TemAtualAAjLabel.setVisible(true);
                TempjButton.setVisible(true);
                ValorTempAtualjLabel1.setVisible(true);
                jTextField1.setVisible(true);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PowerAAjButton1ActionPerformed

    private void TempjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempjButtonActionPerformed

        try {
            aaController.changeTemperature(Float.valueOf(jTextField1.getText()));

            ValorTempAtualjLabel1.setText(String.valueOf(aaController.getAquecedor().getTemperature()));
        } catch (RemoteException ex) {
            Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TempjButtonActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="ArCondicionado">
    private void PowerACjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerACjButton2ActionPerformed

        try {
            acController.turnOffOn();

            if (!acController.getArCondicionado().isPowerButton()) {
                ValorLigaDesligajLabel3.setText("Desligado");
                PowerACjButton2.setText("Liga");

                TemperaturaAtualjLabel1.setVisible(false);
                ValorTempAtualjLabel2.setVisible(false);
                jTextField2.setVisible(false);
                
                TempjButton1.setVisible(false);
                WindjButton1.setVisible(false);
                WindjLabel.setVisible(false);
                ValorVentojLabel1.setVisible(false);

            } else {
                ValorLigaDesligajLabel3.setText("Ligado");
                PowerACjButton2.setText("Desliga");

                TemperaturaAtualjLabel1.setVisible(true);
                TempjButton1.setVisible(true);
                ValorTempAtualjLabel2.setVisible(true);
                jTextField2.setVisible(true);

                WindjButton1.setVisible(true);
                WindjLabel.setVisible(true);
                ValorVentojLabel1.setVisible(true);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PowerACjButton2ActionPerformed

    private void TempjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempjButton1ActionPerformed

        try {
            acController.changeTemperature(Float.valueOf(jTextField1.getText()));
            ValorTempAtualjLabel1.setText(String.valueOf(acController.getArCondicionado().getTemperature()));
        } catch (RemoteException ex) {
            Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TempjButton1ActionPerformed

    private void WindjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WindjButton1ActionPerformed

        try {
            acController.turnWindOffOn();

            if (!acController.getArCondicionado().isWind()) {
                ValorVentojLabel1.setText("Desligado");
                WindjButton1.setText("Liga");
            } else {
                ValorVentojLabel1.setText("Ligado");
                WindjButton1.setText("Desliga");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_WindjButton1ActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Ligth">
    private void PowerjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerjButton3ActionPerformed

        try {
            liController.turnOffOn();

            if (!liController.getLight().isPowerButton()) {
                ValorLigaDesligajLabel1.setText("Desligado");
                PowerjButton.setText("Liga");

                IntensidadejLabel.setVisible(false);
                IntensidadejButton.setVisible(false);
                ValorIntensidadejLabel.setVisible(false);
                IntensidadejTextField1.setVisible(false);

            } else {
                ValorLigaDesligajLabel1.setText("Ligado");
                PowerjButton.setText("Desliga");

                IntensidadejLabel.setVisible(true);
                IntensidadejButton.setVisible(true);
                ValorIntensidadejLabel.setVisible(true);
                IntensidadejTextField1.setVisible(true);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PowerjButton3ActionPerformed

    private void IntensidadejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntensidadejButtonActionPerformed

        try {
            liController.changeIntensity(Integer.parseInt(IntensidadejTextField1.getText()));
            ValorIntensidadejLabel.setText(String.valueOf(liController.getLight().getIntensity()));
        } catch (RemoteException ex) {
            Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IntensidadejButtonActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="SmartDoor">
    private void SenhajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhajButtonActionPerformed
        try {
            String pwd = this.SenhajTextField.getText();
            if (this.sdController.checkPassword(pwd)) {
                ValorPortajLabel1.setText("Aberta");

                FecharPortajButton1.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Senha Inválida!");
            }

            SenhajTextField.setText("");
        } catch (RemoteException ex) {
            Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SenhajButtonActionPerformed

    private void FecharPortajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharPortajButton1ActionPerformed
        try {
            this.sdController.closeDoor();
            ValorPortajLabel1.setText("Fechada");
            FecharPortajButton1.setVisible(false);
        } catch (RemoteException ex) {
            Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FecharPortajButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    //</editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Smart_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Smart_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Smart_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Smart_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Smart_Home().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Smart_Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppjLabel;
    private javax.swing.JButton CanaljButton;
    private javax.swing.JLabel CanaljLabel;
    private javax.swing.JTextField CanaljTextField1;
    private javax.swing.JButton FecharPortajButton1;
    private javax.swing.JButton IntensidadejButton;
    private javax.swing.JLabel IntensidadejLabel;
    private javax.swing.JTextField IntensidadejTextField1;
    private javax.swing.JLabel LigaDesligajLabel;
    private javax.swing.JLabel LigaDesligajLabel1;
    private javax.swing.JLabel LigaDesligajLabel2;
    private javax.swing.JLabel LigaDesligajLabel3;
    private javax.swing.JButton PowerAAjButton1;
    private javax.swing.JButton PowerACjButton2;
    private javax.swing.JButton PowerjButton;
    private javax.swing.JButton PowerjButton3;
    private javax.swing.JButton SenhajButton;
    private javax.swing.JLabel SenhajLabel;
    private javax.swing.JTextField SenhajTextField;
    private javax.swing.JLabel TemAtualAAjLabel;
    private javax.swing.JLabel TemperaturaAtualjLabel1;
    private javax.swing.JButton TempjButton;
    private javax.swing.JButton TempjButton1;
    private javax.swing.JLabel ValorCanaljLabel;
    private javax.swing.JLabel ValorIntensidadejLabel;
    private javax.swing.JLabel ValorLigaDesligajLabel1;
    private javax.swing.JLabel ValorLigaDesligajLabel2;
    private javax.swing.JLabel ValorLigaDesligajLabel3;
    private javax.swing.JLabel ValorLigaDesligajLabel4;
    private javax.swing.JLabel ValorPortajLabel1;
    private javax.swing.JLabel ValorTempAtualjLabel1;
    private javax.swing.JLabel ValorTempAtualjLabel2;
    private javax.swing.JLabel ValorVentojLabel1;
    private javax.swing.JLabel ValorVolumejLabel1;
    private javax.swing.JButton VolumejButton1;
    private javax.swing.JLabel VolumejLabel;
    private javax.swing.JTextField VolumejTextField;
    private javax.swing.JButton WindjButton1;
    private javax.swing.JLabel WindjLabel;
    private javax.swing.JPanel abaAquecedor;
    private javax.swing.JPanel abaAr;
    private javax.swing.JPanel abaHome;
    private javax.swing.JPanel abaLuz;
    private javax.swing.JPanel abaPorta;
    private javax.swing.JPanel abaTV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
