package jokenpo.view;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jokenpo.jogo.JogadorCpu;
import jokenpo.jogo.DadosJogador;
import jokenpo.jogo.Jogador;
import jokenpo.jogo.JogadorLocal;
import jokenpo.jogo.JogadorRemoto;
import jokenpo.jogo.Sessao;
import jokenpo.rmi.ServidorSala;
import jokenpo.rmi.ServidorSessao;

public class JokenpoPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Jokenpo
     */
    public JokenpoPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNomeUserPrincipal = new javax.swing.JLabel();
        jTextFieldNomeUserPrincipal = new javax.swing.JTextField();
        jLabelNomeAdPrincipal = new javax.swing.JLabel();
        jButtonCPU = new javax.swing.JButton();
        jButtonOnline = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabelNomeUserPrincipal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelNomeUserPrincipal.setText("Digite seu nome:");

        jTextFieldNomeUserPrincipal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabelNomeAdPrincipal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelNomeAdPrincipal.setText("Escolha seu adversário:");

        jButtonCPU.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonCPU.setText("CPU");
        jButtonCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCPUActionPerformed(evt);
            }
        });

        jButtonOnline.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonOnline.setText("Online");
        jButtonOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOnlineActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("JoKenPô!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabelNomeUserPrincipal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jButtonCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelNomeAdPrincipal)
                            .addComponent(jTextFieldNomeUserPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabelNomeUserPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeUserPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabelNomeAdPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonCPU)
                    .addComponent(jButtonOnline))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCPUActionPerformed
        String meuNome = jTextFieldNomeUserPrincipal.getText();
        String meuId = UUID.randomUUID().toString();

        if (!meuNome.equals("")) {
            Jogador jogador1 = new JogadorLocal(meuId, meuNome);
            Jogador jogador2 = new JogadorCpu();
            
            Sessao sessaoLocal = new Sessao(jogador1, jogador2);
            
            JokenpoPlay telaJogar = new JokenpoPlay(sessaoLocal, this, null);
            this.setVisible(false);
            telaJogar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Escreva seu nome!");
        }
    }//GEN-LAST:event_jButtonCPUActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        System.out.println("Ativada");
    }//GEN-LAST:event_formWindowActivated

    private void jButtonOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOnlineActionPerformed
        ServidorSala servidorSala = null;
        ServidorSessao servidorSessao = null;

        String meuNome = jTextFieldNomeUserPrincipal.getText();
        String meuId = UUID.randomUUID().toString();
        if (!meuNome.equals("")) {
            
            try {
                servidorSala = (ServidorSala) Naming.lookup("rmi://LOCALHOST:2210/Sala");
                servidorSessao = (ServidorSessao) Naming.lookup("rmi://LOCALHOST:2210/Sessao");
                
                servidorSessao.conectar(meuId, meuNome);
            } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                Logger.getLogger(JokenpoPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            DadosJogador adversario = null;
            boolean conectado = false;
            int tentativas = 10;
            
            do {
                tentativas--;
                
                try {
                    adversario = servidorSessao.buscarAdversario(meuId);
                    conectado = true;
                } catch (RemoteException ex) {
                    System.out.println("Buscando adversarios...");
                    
                    try {
                        Thread.sleep(5000);
                    } catch (InterruptedException ex1) {
                        Logger.getLogger(JokenpoPrincipal.class.getName()).log(Level.SEVERE, null, ex1);
                    }
                }
                
            } while (conectado == false && tentativas >= 0);
            
            if (conectado && adversario != null) {
                
                Jogador jogador1 = new JogadorLocal(meuId, meuNome, servidorSala);
                Jogador jogador2 = new JogadorRemoto(servidorSala, adversario);
                
                Sessao sessaoRemota = new Sessao(jogador1, jogador2);
                
                JokenpoPlay telaJogar = new JokenpoPlay(sessaoRemota, this, servidorSessao);
                this.setVisible(false);
                telaJogar.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "Não encontramos adversarios disponiveis", null, JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Escreva seu nome!");
        }
    }//GEN-LAST:event_jButtonOnlineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JokenpoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JokenpoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JokenpoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JokenpoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JokenpoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCPU;
    private javax.swing.JButton jButtonOnline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNomeAdPrincipal;
    private javax.swing.JLabel jLabelNomeUserPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNomeUserPrincipal;
    // End of variables declaration//GEN-END:variables
}
