package jokenpo.view;

import java.awt.HeadlessException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jokenpo.jogo.Sessao;
import jokenpo.rmi.ServidorSessao;

public class JokenpoPlay extends javax.swing.JFrame {

    private final Sessao sessao;
    private final JokenpoPrincipal telaPrincipal;
    private final ServidorSessao servidorSessao;
    private final Thread threadVerificador;

    public JokenpoPlay(Sessao sessao, JokenpoPrincipal telaPrincipal, ServidorSessao servidorSessao) {
        this.sessao = sessao;
        this.telaPrincipal = telaPrincipal;
        this.servidorSessao = servidorSessao;

        initComponents();

        jLabelNomeUserPlay.setText(sessao.getJogador1().getDadosJogador().getNome());
        jLabelNomeAdvPlay.setText(sessao.getJogador2().getDadosJogador().getNome());

        if (servidorSessao != null) {
            VerificadorThread verificador = new VerificadorThread(servidorSessao, sessao.getJogador2().getDadosJogador().getId(), this);
            threadVerificador = new Thread(verificador);
            threadVerificador.start();
        }else{
            threadVerificador = null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTxtPontosUser = new javax.swing.JLabel();
        jLabelValorPontosUser = new javax.swing.JLabel();
        jLabelTxtPontosAdv = new javax.swing.JLabel();
        jLabelValorPontosAdv = new javax.swing.JLabel();
        jLabelNomeUserPlay = new javax.swing.JLabel();
        jLabelNomeAdvPlay = new javax.swing.JLabel();
        jLabelTxtJogadas = new javax.swing.JLabel();
        jLabelValorJogadas = new javax.swing.JLabel();
        jButtonFinalizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonNovaJogada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTxtPontosUser.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelTxtPontosUser.setText("Pontos:");

        jLabelValorPontosUser.setBackground(new java.awt.Color(243, 243, 243));
        jLabelValorPontosUser.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabelValorPontosUser.setText("0");

        jLabelTxtPontosAdv.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelTxtPontosAdv.setText("Pontos:");

        jLabelValorPontosAdv.setBackground(new java.awt.Color(243, 243, 243));
        jLabelValorPontosAdv.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabelValorPontosAdv.setText("0");

        jLabelNomeUserPlay.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabelNomeUserPlay.setText("Usuario");

        jLabelNomeAdvPlay.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabelNomeAdvPlay.setText("Adversario");

        jLabelTxtJogadas.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabelTxtJogadas.setText("Jogadas:");

        jLabelValorJogadas.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabelValorJogadas.setText("0");

        jButtonFinalizar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("JoKenPô!");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setText("VS");

        jButtonNovaJogada.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonNovaJogada.setText("Nova Jogada");
        jButtonNovaJogada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaJogadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelNomeUserPlay)
                    .addComponent(jLabelTxtPontosUser)
                    .addComponent(jLabelValorPontosUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelTxtPontosAdv)
                    .addComponent(jLabelValorPontosAdv)
                    .addComponent(jLabelNomeAdvPlay))
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonNovaJogada, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabelTxtJogadas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelValorJogadas))
                                .addComponent(jButtonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabelNomeUserPlay)
                            .addComponent(jLabelNomeAdvPlay, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTxtPontosUser)
                            .addComponent(jLabelTxtPontosAdv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelValorPontosUser)
                            .addComponent(jLabelValorPontosAdv)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNovaJogada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTxtJogadas)
                    .addComponent(jLabelValorJogadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFinalizar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovaJogadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaJogadaActionPerformed
        sessao.novaRodada();

        jLabelValorPontosUser.setText(String.valueOf(sessao.getJogador1().getDadosJogador().getPontuacao()));
        jLabelValorPontosAdv.setText(String.valueOf(sessao.getJogador2().getDadosJogador().getPontuacao()));

        jLabelValorJogadas.setText(String.valueOf(sessao.getNumRodadas()));
    }//GEN-LAST:event_jButtonNovaJogadaActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        if (threadVerificador != null) {
            threadVerificador.interrupt();
        }
        desconectar();
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JokenpoPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JokenpoPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JokenpoPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JokenpoPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JokenpoPlay().setVisible(true);
//            }
//        });
//    }
    public void desconectar() throws HeadlessException {
        int pontosJ1 = sessao.getJogador1().getDadosJogador().getPontuacao();
        int pontosJ2 = sessao.getJogador2().getDadosJogador().getPontuacao();

        if (pontosJ1 > pontosJ2) {
            JOptionPane.showMessageDialog(this, "Parabéns!!! Você ganhou!", "Resultado da sessão", JOptionPane.PLAIN_MESSAGE);
        } else if (pontosJ1 < pontosJ2) {
            JOptionPane.showMessageDialog(this, "Que pena, você perdeu para " + sessao.getJogador2().getDadosJogador().getNome(), "Resultado da sessão", JOptionPane.PLAIN_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "O jogo empatou!", "Resultado da sessão", JOptionPane.PLAIN_MESSAGE);
        }

        if (servidorSessao != null) {
            try {
                servidorSessao.desconectar(sessao.getJogador1().getDadosJogador().getId());
            } catch (RemoteException ex) {
                Logger.getLogger(JokenpoPlay.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        this.setVisible(false);
        telaPrincipal.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonNovaJogada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNomeAdvPlay;
    private javax.swing.JLabel jLabelNomeUserPlay;
    private javax.swing.JLabel jLabelTxtJogadas;
    private javax.swing.JLabel jLabelTxtPontosAdv;
    private javax.swing.JLabel jLabelTxtPontosUser;
    private javax.swing.JLabel jLabelValorJogadas;
    private javax.swing.JLabel jLabelValorPontosAdv;
    private javax.swing.JLabel jLabelValorPontosUser;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
